name: Build and Release (Windows x64)

on:
#  push:
#    tags:
#      - '1*'
#      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build:windows:x64  # Replace with your actual build command

      - name: Archive Build Outputs
        run: |
          mkdir -p artifacts
          Compress-Archive -Path builds\* -DestinationPath artifacts\Windows_x64-Build.zip
        shell: pwsh

      - name: Debug Step -- Confirm ZIP File Exists
        shell: pwsh
        run: |
          if (Test-Path -Path ./artifacts/Windows_x64-Build.zip) {
            Write-Host "ZIP file exists at ./artifacts/Windows_x64-Build.zip"
          } else {
            Write-Error "ZIP file not found at ./artifacts/Windows_x64-Build.zip"
            exit 1
          }

      - name: Extract Release Tag
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -like 'refs/tags/*') {
            $TAG_NAME = $env:GITHUB_REF -replace '^refs/tags/', ''
            Write-Host "Extracted TAG_NAME: $TAG_NAME"
            echo "TAG_NAME=$TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          } else {
            Write-Error "GITHUB_REF does not contain a valid tag. Received: $env:GITHUB_REF"
            exit 1
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/Windows_x64-Build.zip  # Upload the .zip file
          tag_name: ${{ env.TAG_NAME }}
          name: Unifi Protect Viewer ${{ env.TAG_NAME }}
          body: |
            Automated Release for Windows Archive (x64) - version ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
